name: Python Pytest CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Pythonをセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: pipをアップグレード
        run: python -m pip install --upgrade pip

      - name: ライブラリをインストール
        run: pip install -r requirements.txt

      - name: Pytestでテスト実行
        run: pytest

  manual-approval:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}
    environment:
      name: production
  

    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Setup Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Run tests again（マージ前に念のためテスト）
          run: pytest